# Generated by Django 4.1.7 on 2023-06-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('patient_email', models.EmailField(max_length=30, unique=True)),
                ('contact', models.BigIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineLearningData',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fever', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('body_aches', models.BooleanField()),
                ('chills', models.BooleanField()),
                ('sweating', models.BooleanField()),
                ('headache', models.BooleanField()),
                ('nausea', models.BooleanField()),
                ('vomiting', models.BooleanField()),
                ('weight_loss', models.BooleanField()),
                ('night_sweats', models.BooleanField()),
                ('weakness', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('abdominal_pain', models.BooleanField()),
                ('diarrhea', models.BooleanField()),
                ('dehydration', models.BooleanField(default=False)),
                ('rash', models.BooleanField()),
                ('muscle_pain', models.BooleanField()),
                ('back_pain', models.BooleanField()),
                ('stiff_neck', models.BooleanField()),
                ('confusion', models.BooleanField()),
                ('runny_nose', models.BooleanField()),
                ('tiredness', models.BooleanField()),
                ('shortness_of_breath', models.BooleanField()),
                ('loss_of_appetite', models.BooleanField()),
                ('chest_pain', models.BooleanField()),
                ('wheezing', models.BooleanField()),
                ('disease', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('disease', models.CharField(max_length=255, unique=True)),
                ('medicine', models.CharField(max_length=255, null=True)),
                ('supportive_care', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=255, unique=True)),
                ('prompt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('body_aches', models.BooleanField()),
                ('chills', models.BooleanField()),
                ('sweating', models.BooleanField()),
                ('headache', models.BooleanField()),
                ('nausea', models.BooleanField()),
                ('vomiting', models.BooleanField()),
                ('weight_loss', models.BooleanField()),
                ('night_sweats', models.BooleanField()),
                ('weakness', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('abdominal_pain', models.BooleanField()),
                ('diarrhea', models.BooleanField()),
                ('dehydration', models.BooleanField(default=False)),
                ('rash', models.BooleanField()),
                ('muscle_pain', models.BooleanField()),
                ('back_pain', models.BooleanField()),
                ('stiff_neck', models.BooleanField()),
                ('confusion', models.BooleanField()),
                ('runny_nose', models.BooleanField()),
                ('tiredness', models.BooleanField()),
                ('shortness_of_breath', models.BooleanField()),
                ('loss_of_appetite', models.BooleanField()),
                ('chest_pain', models.BooleanField()),
                ('wheezing', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
