# Generated by Django 4.1.7 on 2023-06-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsigns',
            name='dehydration',
            field=models.BooleanField(default=False),
        ),
    ]
