# Generated by Django 4.1.7 on 2023-06-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('disease', models.CharField(max_length=255, unique=True)),
                ('medicine', models.CharField(max_length=255)),
            ],
        ),
    ]
