# Generated by Django 4.1.7 on 2023-06-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='supportive_care',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
