# Generated by Django 4.1.7 on 2023-06-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_medication_supportive_care_alter_medication_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsigns',
            name='laundice',
        ),
        migrations.RemoveField(
            model_name='patientsigns',
            name='seizures',
        ),
        migrations.RemoveField(
            model_name='patientsigns',
            name='swollen_lymph_nodes',
        ),
        migrations.RemoveField(
            model_name='patientsigns',
            name='swollen_salivary_glands',
        ),
    ]
