# Generated by Django 4.1.7 on 2023-06-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_patientsigns_laundice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsigns',
            name='conjunctivities',
        ),
    ]
