# Generated by Django 4.1.7 on 2023-07-01 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('inputID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('input', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
