# Generated by Django 4.1.7 on 2023-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_doctor_doctorid_inputfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
