# Generated by Django 4.1.7 on 2023-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latiitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
