# Generated by Django 4.1.7 on 2023-07-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_doctor_latiitude_alter_doctor_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latiitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
