# Generated by Django 4.1.7 on 2023-07-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_doctor_latiitude_alter_doctor_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='latiitude',
            new_name='latitude',
        ),
    ]
