# Generated by Django 4.1.7 on 2023-07-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mlmodeldata_usersignsnsymptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodeldata',
            name='shortness_of_breath',
        ),
    ]
