# Generated by Django 4.1.7 on 2023-07-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_usersignsnsymptoms_shortness_of_breath'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPTable',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=255)),
                ('synonymn_1', models.CharField(max_length=255)),
                ('synonymn_2', models.CharField(max_length=255)),
                ('synonymn_3', models.CharField(max_length=255)),
                ('synonymn_4', models.CharField(max_length=255)),
                ('synonymn_5', models.CharField(max_length=255)),
            ],
        ),
    ]
