# Generated by Django 4.1.7 on 2023-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_nlptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlptable',
            name='synonymn_6',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
