# Generated by Django 4.1.7 on 2023-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_usersignsnsymptoms_abdominal_pain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignsnsymptoms',
            name='swollen_legs',
            field=models.BooleanField(null=True),
        ),
    ]
