# Generated by Django 4.1.7 on 2023-07-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_usersignsnsymptoms_swollen_legs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsViewed',
            fields=[
                ('doctorsViewed_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
