# Generated by Django 4.1.7 on 2023-07-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_doctorsviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feeback_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('feedback', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
