# Generated by Django 4.1.7 on 2023-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInformation',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('disease', models.CharField(max_length=255)),
                ('causes', models.CharField(max_length=2000)),
                ('symptoms', models.CharField(max_length=2000)),
                ('preventive_measures', models.CharField(max_length=2000)),
            ],
        ),
    ]
