# Generated by Django 4.1.7 on 2023-07-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_diseaseinformation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseinformation',
            name='description',
        ),
    ]
