# Generated by Django 4.1.7 on 2023-07-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_diseaseinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='input',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
