# Generated by Django 4.1.7 on 2023-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfield',
            name='input',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
