# Generated by Django 4.1.7 on 2023-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_inputfield_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignsnsymptoms',
            name='predicted_disease',
            field=models.CharField(default='', max_length=255),
        ),
    ]
