# Generated by Django 4.1.7 on 2023-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_usersignsnsymptoms_date_diagonised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignsnsymptoms',
            name='date_diagonised',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
