# Generated by Django 4.1.7 on 2023-07-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_machinelearningmodeldata_nlplookuptable_usersymptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinelearningmodeldata',
            name='loss_of_balance',
        ),
        migrations.RemoveField(
            model_name='usersymptoms',
            name='loss_of_balance',
        ),
    ]
