# Generated by Django 4.1.7 on 2023-07-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_usersymptoms_abdominal_pain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feeback_id',
            new_name='feedback_id',
        ),
    ]
