# Generated by Django 4.1.7 on 2023-07-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_delete_sign_rename_feeback_id_feedback_feedback_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersymptoms',
            old_name='patient_sign_id',
            new_name='symptom_id',
        ),
    ]
