# Generated by Django 4.1.7 on 2023-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_patient_sign_id_usersymptoms_symptom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='classification',
            field=models.CharField(default='Positive', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=2000),
        ),
    ]
