# Generated by Django 4.1.7 on 2023-07-15 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_feedback_classification_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 10, 15, 34, 552839)),
        ),
    ]
