# Generated by Django 4.1.7 on 2023-07-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_paymenttransaction_delete_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patient_email',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
