# Generated by Django 4.1.7 on 2023-07-16 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rename_patient_email_customuser_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='data_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
