# Generated by Django 4.1.7 on 2023-07-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_paymenttransaction_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
