# Generated by Django 4.1.7 on 2023-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_paymenttransaction_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
