# Generated by Django 4.1.7 on 2023-07-17 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_paymenttransaction_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionApproval',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('merchant_request_id', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.TextField()),
                ('amount', models.IntegerField()),
                ('mpesa_receipt_number', models.CharField(max_length=30)),
                ('transaction_date', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
